version: '3'
networks:
  ext:
  exterior:
  proxy:
    external:
      name: biller_proxy
  dbnet:
    internal: true

services:
  merge:
    build:
      context: ./app/01merge/
      dockerfile: Dockerfile
    container_name: sso-merge
    tty: true
    restart: always
    depends_on:
      front:
        condition: "service_started"
    networks:
      - exterior
      - proxy
    ports:
      - 8888:80
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 80

  front:
    build:
      context: ./app/02front/
      dockerfile: Dockerfile
    container_name: sso-front
    tty: true
    restart: always
    networks:
      - proxy
    expose:
      - 80
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./app/02front/src/src/:/usr/share/nginx/html:ro

  back:
    build:
      context: ./app/03back
      dockerfile: Dockerfile
    container_name: sso-back
    tty: true
    restart: always
    depends_on:
      rethink:
        condition: "service_started"
    networks:
      - proxy
      - dbnet
    expose:
      - 8080
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./app/03back/src:/home/api:ro

  rethink:
    build:
      context: ./app/05rethink
      dockerfile: Dockerfile
    container_name: sso-rethink
    restart: always
    ports:
      - 8887:8080
    expose:
      - 28015
    # volumes:
    #   - ./database:/data
    # command: rethinkdb --bind all -d /data
    networks:
      - dbnet
      - ext
